name: Deploy API to Railway

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
      - '.github/workflows/railway-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Install deps
        run: npm ci

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          if [ -z "$RAILWAY_TOKEN" ]; then
            echo "::error::RAILWAY_TOKEN secret is not set"
            echo "Please add RAILWAY_TOKEN to: https://github.com/Authenticai-agent/ausratravel/settings/secrets/actions"
            exit 1
          fi
          
          # Railway CLI uses RAILWAY_TOKEN automatically when set
          export RAILWAY_TOKEN
          
          # Link project if PROJECT_ID is provided and not already linked
          if [ -n "$RAILWAY_PROJECT_ID" ] && [ ! -f .railway/project.json ]; then
            echo "Linking Railway project..."
            railway link "$RAILWAY_PROJECT_ID" --non-interactive || true
          fi
          
          # Deploy
          railway up --detach


