name: Deploy API to Railway

# Note: This workflow is a fallback option.
# Recommended: Use Railway's native GitHub integration for automatic deployments.
# See RAILWAY_DEPLOYMENT.md for setup instructions.

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
      - '.github/workflows/railway-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Railway CLI
        run: npm i -g @railway/cli@latest

      - name: Install deps
        run: npm ci

      - name: Deploy to Railway via CLI
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          if [ -z "$RAILWAY_TOKEN" ]; then
            echo "::warning::RAILWAY_TOKEN not set. Skipping CLI deployment."
            echo "::notice::Consider using Railway's native GitHub integration instead."
            echo "See RAILWAY_DEPLOYMENT.md for instructions."
            exit 0
          fi
          
          # Railway CLI uses RAILWAY_TOKEN for authentication
          # Note: Railway's native GitHub integration is recommended instead of CLI in CI/CD
          echo "Attempting Railway CLI deployment..."
          railway up --service ausratravel --detach || {
            echo "::warning::Railway CLI deployment failed."
            echo "::notice::Railway's native GitHub integration is recommended for automatic deployments."
            echo "Your code has been pushed. Railway will auto-deploy if GitHub integration is enabled."
            exit 0
          }


