name: Deploy API to Railway

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
      - '.github/workflows/railway-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Install deps
        run: npm ci

      - name: Create deployment archive
        run: |
          tar -czf deploy.tar.gz .
      
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          if [ -z "$RAILWAY_TOKEN" ]; then
            echo "::error::RAILWAY_TOKEN secret is not set"
            echo "Please add RAILWAY_TOKEN to: https://github.com/Authenticai-agent/ausratravel/settings/secrets/actions"
            exit 1
          fi
          
          if [ -z "$RAILWAY_PROJECT_ID" ]; then
            echo "::error::RAILWAY_PROJECT_ID secret is not set"
            exit 1
          fi
          
          # Use Railway CLI with explicit project/service specification
          # Create .railway config file
          mkdir -p .railway
          cat > .railway/project.json << EOF
          {
            "project": {
              "id": "$RAILWAY_PROJECT_ID"
            },
            "environment": {
              "name": "production"
            },
            "service": {
              "name": "ausratravel"
            }
          }
          EOF
          
          # Deploy using Railway CLI with token
          RAILWAY_TOKEN="$RAILWAY_TOKEN" railway up --service ausratravel --detach


